### ISSUE TITLE
The structure of the repo in the nixos

### ISSUE THREAD

**Issue by Leandro-Dalla-Nora** [Frost-Phoenix/nixos-config#1]
Hy! I'm Leandro. How are you?

In my search of dotfiles for hyprland, i find your repo, and it's so good, and the organization of your files is very insteresting, clear and beautiful. 

1 - The post install of your dotfiles, the modules, that contains the softwares and the general configurations of nixos, are target to the /etc/nixos/ ?  

2 - I don't find the configuration.nix. The nixos necessarily this file or he can access the files.nix in the /etc/nixos/ ? 

Thank you! Good week!

**Comment by Frost-Phoenix** [comment]
Great, thanks for checking my config.

So in this config I use nixos flakes which is an experimental feature, so there is no configuration.nix file but a flake.nix file that is the base of the config, and it calls all the other files. I also use home manager which is a nix feature to handle your .config folder declaratively, so you can configure all you app directly in your nix config. 

And with flakes you can put this files and folder where you want in your system, they don't need to be in /etc/nixos, but the command to build the config is different, you need to use `sudo nixos-rebuild switch --flake .#nixos` while being at the root of the repo (the . in .#nixos represent the directory in which the flake.nix file is).

I'm pretty new to nixos and flakes myself, but if you have any more questions, feel free to ask.
