### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by inithinx** [Frost-Phoenix/nixos-config#2]
This project has really interested me. An installation guide would be really welcome, especially for people new to nixos

**Comment by Frost-Phoenix** [comment]
I have planed to do it this week end, will be done today or tomorrow.

**Comment by Frost-Phoenix** [comment]
It's done !  

The installation section of the readme is finished. It explains the installation process as well as how the `install.sh` scripts works.
If you have any further questions about it, feel free to ask.

And if you find everything's ok you can close the issue.
