### ISSUE TITLE
Spicetify add

### ISSUE THREAD

**Issue by codeskin-r** [Frost-Phoenix/nixos-config#22]
I need to bother you one more time because I'm really confused. What would be the correct way to add Spicetify-cli to the configuration correctly?

For example, how to use this config? 

 [https://github.com/Gerg-L/spicetify-nix?tab=readme-ov-file#import-the-module](url)

Pls, help me! 
I've been trying to understand this for a long time hahaha

**Comment by Frost-Phoenix** [comment]
No problem :)

I actually didn't know this spotify client, it's quite good.
So after looking at the link you provided and other configs I figured out how to add it to my config and added it in the latest commit ([f5c5118](https://github.com/Frost-Phoenix/nixos-config/commit/f5c5118938b14f2005adaed2cd9196c6a56eb8bd)). You can see the git diff and look up the files to see how it is done. 

If you have further questions I will be happy to help you.

**Comment by Frost-Phoenix** [comment]
You don't need to worry about the `flake.lock` file, it will be generated automatically when you rebuild the config.

**Comment by codeskin-r** [comment]
> You don't need to worry about the `flake.lock` file, it will be generated automatically when you rebuild the config.

I'm going to take a look at it, thank you very much for your help, I'm glad that the configuration I gave you helped you, the truth is it's more pleasant this way, spotify + spicetify.
