### ISSUE TITLE
Noob Question: How to add a new browser.nix file to home-manager config ?

### ISSUE THREAD

**Issue by artur-pf** [Frost-Phoenix/nixos-config#27]
Hi there,

i tried to add a custom `browser.nix` in the` modules/home/default.nix` and get the Error `Could not Find the File or Directory` if i execute `nix-switch`

my addition in the default.nix
```
...
++  [(import ./browser.nix)];
```

The code within works perfectly if i add in the a other module, so this is probably not the issue:
browser.nix
```
programs.chromium = {
   enable = true;
};
```
Do i need a special command so it gets recognized ?

**Comment by Frost-Phoenix** [comment]
> Do i need a special command so it gets recognized ?

Actually yes, you need to add it to git to let nix know that the file exist.
You can simply do it with `git add .` at the root of the repo.

**Comment by artur-pf** [comment]
This was it, thanks bro 🙏 Are there any guide you used to create this project ?. Would be very helpful for a beginner 👀

**Comment by Frost-Phoenix** [comment]
> Are there any guide you used to create this project ?

Not one thing in particular but I highly recommend you check [Vimjoyer's](https://www.youtube.com/@vimjoyer) channel, all of its videos are really good.

Also whenever you want to search for an option or how to configure a package you can use the github search, it is very powerful. In the search bar you can put `language:nix` before the thing you want to find and then in the code section you will see how other people use the options/program. It will give you a good starting point on what you want to do.
