### ISSUE TITLE
Issues with copy pasting

### ISSUE THREAD

**Issue by thomas-rooty** [Frost-Phoenix/nixos-config#34]
Hello,

First off thank you for your amazing work, the design and everything is sorted perfectly. But Im encountering issues with copy pasting, I can't really explain when and why but whenever I try to copy something from brave on workspace 1, switch to workspace 2 and paste it into VSC it just pastes something empty

Also, when I copy something from Brave I can't paste it in Brave itself, and I can't copy something from VSC to Brave neither even if they're on the same workspace or not.

It seems to work at first when I bootup or when I nixos switch, but whenever I switch to brave it just starts to get messy

Sorry for the lack of logs or anything else, I just don't really know myself whats happening

**Comment by Balssh** [comment]
Hi there, I think it may be due to Brave, I'm using Firefox with these dots and it works without issues.

**Comment by thomas-rooty** [comment]
It seems it was an issue cause by xwayland/wayland apps, I tried to launch brave as a wayland app and it worked flawlessly, thus I did not wanted to go through that pain for each app, I switch to another clipboard manager copyq. Everything is working fine since then
