### ISSUE TITLE
Can't rebuild my system

### ISSUE THREAD

**Issue by vSAQv** [Frost-Phoenix/nixos-config#35]
Hello), I am new to NixOS(so maybe i can't see something very obvious),  I just installed your rice and don't understand why those errors happening. 
When I'am trying: nix-env --upgrade 
i've got a lot of errors:
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpathHook instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpathHook instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpathHook instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: eww now can build for X11 and wayland simultaneously, so `eww-wayland` is deprecated, use the normal `eww` package instead.
trace: warning: lxd has been renamed to lxd-lts
trace: warning: lxd-unwrapped has been renamed to lxd-unwrapped-lts
trace: warning: nixfmt was renamed to nixfmt-classic. The nixfmt attribute may be used for the new RFC 166-style formatter in the future, which is currently available as nixfmt-rfc-style
trace: warning: nvtop has been renamed to nvtopPackages.full
trace: warning: nvtop-amd has been renamed to nvtopPackages.amd
trace: warning: nvtop-intel has been renamed to nvtopPackages.intel
trace: warning: nvtop-msm has been renamed to nvtopPackages.msm
trace: warning: nvtop-nvidia has been renamed to nvtopPackages.nvidia
trace: warning: 'rapidjson-unstable' has been renamed to 'rapidjson'
trace: warning: writeReferencesToFile is deprecated in favour of writeClosure

Do i actually have to change all those package names to new ones ? Or is there a major error which is the cause of others?
And second problem is...
When I'am trying:
nixos-rebuild switch --upgrade
I am getting another pack of errors:
unpacking channels...
error:
       … while evaluating the attribute 'config'

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:334:9:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          335|         _module = checked (config._module);

       … while calling the 'seq' builtin

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:334:18:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
building Nix...
error:
       … while evaluating the attribute 'config'

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:334:9:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          335|         _module = checked (config._module);

       … while calling the 'seq' builtin

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:334:18:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
building the system configuration...
error:
       … while evaluating the attribute 'config.system.build.toplevel'

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:334:9:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          335|         _module = checked (config._module);

       … while calling the 'seq' builtin

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:334:18:

          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)

I've listed channels,  and since list was empty I added current stable one, and unstable one. Now when I try nix-env --update it gives even more errors:
trace: evaluation warning: The package set `androidndkPkgs_23b` has been renamed to `androidndkPkgs_23`.
trace: evaluation warning: cinnamon.bulky was moved to top-level. Please use pkgs.bulky directly.
trace: evaluation warning: cinnamon.cinnamon-common was moved to top-level. Please use pkgs.cinnamon-common directly.
and so on...

**Comment by Frost-Phoenix** [comment]
How did you install ?
Did you follow the install section in the README or dud you install differently, and if so how ?

**Comment by vSAQv** [comment]
> How did you install ?
> 
> Did you follow the install section in the README or dud you install differently, and if so how ? 

Yes, I did. I followed installation section precisely. I used gnome iso, and also changed script to reduce number of cores during installation ( first time i tried plasma iso and installation failed ). I don't remember clearly but there could be some warnings while installation.

**Comment by Frost-Phoenix** [comment]
Ok, a few things:
- when you use `nix-env --upgrade` what do you want to do? (I never used it so I don't really know what is does)
- when you use `nixos-rebuild switch --upgrade` you are note rebuilding this config but rather the one in your `/etc/nixos/configuration.nix ` config file (that is because you don't specify --flake with the path to the flake). If you want to rebuild manually you can use `nixos-rebuild switch --flake .#${host}` and replace ${host} to the one you are using (can be either desktop, laptop, or vm), and this command should be executed in the repo you cloned.

Can you try re-cloning the repo and `nixos-rebuild switch --flake .#${host}` inside it to see what could be the problem ?

**Comment by vSAQv** [comment]
About nix-env --upgrade... I just was trying every command that possibly could fix the problem, and thought it's output could be useful. I don't really know what it actually does. 
this is output for manual rebuild without re-cloning:

nixos-rebuild switch --flake ./hosts/laptop
path '/home/cif/nixos-config/hosts/laptop' does not contain a 'flake.nix', searching up
warning: Git tree '/home/cif/nixos-config' is dirty
building the system configuration...
path '/home/cif/nixos-config/hosts/laptop' does not contain a 'flake.nix', searching up
warning: Git tree '/home/cif/nixos-config' is dirty
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 316 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
error:
       … while calling the 'head' builtin

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: program 'git' failed with exit code 128

Can't clone repo for some reason: 
git clone https://github.com/Frost-Phoenix/nixos-config
Cloning into 'nixos-config'...
remote: Enumerating objects: 6690, done.
remote: Counting objects: 100% (1324/1324), done.
remote: Compressing objects: 100% (665/665), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 222 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

I'll try it later on home wifi later...

**Comment by Frost-Phoenix** [comment]
> nixos-rebuild switch --flake ./hosts/laptop

This is not the right command, you need to use `nixos-rebuild switch --flake .#laptop`. The `.` is for the path to the flake (this is why you need to use the command in the repo, where the file `flake.nix` is located) and the `#laptop` specifies that you want to build the laptop config.

> I'll try it later on home wifi later...

Ok, if you want you can also contact me on [discord](https://discord.com/users/593456700045000704), I will respond faster there.
