### ISSUE TITLE
Resolution 

### ISSUE THREAD

**Issue by rares9301** [Frost-Phoenix/nixos-config#40]
Hey. Where exactly can i specify my screen resolution? All apps look really small since i got a 2.8k laptop monitor

**Comment by rares9301** [comment]
Yea, i found that one prior. I thought there was another way through sway config. Will update after i get it working using extraCFG.

**Comment by Frost-Phoenix** [comment]
tbh I never used scaling so don't really know how it work, I just assumed the hyprland config would work...

**Comment by Balssh** [comment]
> Yea, i found that one prior. I thought there was another way through sway config. Will update after i get it working using extraCFG.

You can easily change scaling in hyprland using the monitors option. Did you try it?

**Comment by rares9301** [comment]
Yes. Issue fixed.
