### ISSUE TITLE
Proposal to Replace Screenshot Tool in NixOS Configuration with Swappy

### ISSUE THREAD

**Issue by 0x733** [Frost-Phoenix/nixos-config#41]
Hello,

I’d like to suggest an improvement to your current NixOS configuration by replacing the existing screenshot tool with Swappy. Swappy is a modern, feature-rich screenshot editing tool that offers an intuitive user interface along with annotation capabilities, making it a great choice for enhancing productivity.

Benefits of Using Swappy:

	•	Annotation Features: Swappy allows you to quickly edit and annotate screenshots, including drawing, cropping, and highlighting sections.
	•	Wayland Support: It is optimized for Wayland environments, providing seamless functionality.
	•	Lightweight & Efficient: Swappy is minimal in terms of resource usage, making it a solid replacement for more complex tools.

If you’re looking for a streamlined way to capture and annotate screenshots, Swappy could be an ideal choice for your workflow.

You can check the Swappy repository for more details and installation instructions: [Swappy GitHub Repo](https://github.com/jtheoof/swappy).

Best regards,
Neo

**Comment by Frost-Phoenix** [comment]
Oh that look cool. But I also really like the non intrusive way of the current system, like I can just take a screenshot and past it directly or things like that. But it would cool to have the tow at the same time, like on different keybinds I guess?

**Comment by 0x733** [comment]
> Oh that look cool. But I also really like the non intrusive way of the current system, like I can just take a screenshot and past it directly or things like that. But it would be cool to have the tow at the same time, like on different keybinds I guess?

Oh that look cool. But I also really like the non intrusive way of the current system, like I can just take a screenshot and past it directly or things like that. But it would be cool to have the tow at the same time, like on different keybinds I guess?

**Comment by Frost-Phoenix** [comment]
> It’s definitely worth trying. It could even be left as a comment line to let the user decide.

Oh that a good idea, I think that I will keep the default `Print` keybind to grimblast but maybe `SHIFT Print` could be Swappy, with a comment explaining how to put Swappy as the default one (for the main keybind).
What do you think could be the keybind for Swappy ?

**Comment by 0x733** [comment]
> > It’s definitely worth trying. It could even be left as a comment line to let the user decide.
> 
> 
> 
> Oh that a good idea, I think that I will keep the default `Print` keybind to grimblast but maybe `SHIFT Print` could be Swappy, with a comment explaining how to put Swappy as the default one (for the main keybind).
> 
> What do you think could be the keybind for Swappy ?

The most logical combination seems to be Super + Shift + Print. I can provide examples for configuration ease or reference.

	•	[Keybinds.conf](https://github.com/JaKooLit/Hyprland-Dots/blob/ef5d3ccbb8e7d82a184e36e45d67391aca65082d/config/hypr/configs/Keybinds.conf#L87)
	•	[ScreenShot.sh](https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/scripts/ScreenShot.sh)

**Comment by Frost-Phoenix** [comment]
Ok so took a look at the config you listed and it's pretty cool. 
I added swappy in 9b32101 (for now it is just a test), I used the script you linked but really simplified it.
So now `Super + Shift + Print` takes a screenshot using swappy, and `Print` / `Super + Print` works as befor using just grimblast.

I think like that could be a good way to have both options, with and without swappy, what do you think ?

**Comment by 0x733** [comment]
> Ok so took a look at the config you listed and it's pretty cool. 
> 
> I added swappy in 9b32101 (for now it is just a test), I used the script you linked but really simplified it.
> 
> So now `Super + Shift + Print` takes a screenshot using swappy, and `Print` / `Super + Print` works as befor using just grimblast.
> 
> 
> 
> I think like that could be a good way to have both options, with and without swappy, what do you think ?

I think this should be left to the user. It could remain as a comment or a question could be asked in the install.sh file (although that might be too much, I’m not sure). What do you think?

**Comment by Frost-Phoenix** [comment]
I think a comment in the hyprland + an explanation in the readme should be enough.

**Comment by Frost-Phoenix** [comment]
Also I'm currently trying to find better alternatives for some software and utility, do you have other suggestion ?
Do you think it would be a good idea to open a pined issue to ask for people suggestion on what to add / replace in the config ? Or maybe an other way to gather suggestions ?

**Comment by 0x733** [comment]
> I think a comment in the hyprland + an explanation in the readme should be enough. 

That makes sense; you can certainly proceed that way. Additionally, there’s another point to consider: Are you aiming to keep your NixOS configuration minimal, or are you looking to develop it into something more visually and functionally advanced?

**Comment by 0x733** [comment]
> > Also I'm currently trying to find better alternatives for some software and utility, do you have other suggestion ?
> > 
> > Do you think it would be a good idea to open a pined issue to ask for people suggestion on what to add / replace in the config ? Or maybe an other way to gather suggestions ?
> 
> I was thinking about this topic. Integrating dotfiles into Home Manager can be quite challenging, especially when it comes to visual aspects like selecting themes, changing the style of Waybar, or choosing layouts. Additionally, discussing improvements for Rofi, creating configurations for security software, and sharing ideas for alternative software could be very beneficial. Therefore, opening a pinned issue for these discussions would be a great idea.

Additionally, I tried experimenting with some things in my own Nix files. I didn’t focus on visual aspects, but I attempted to work with tools like Firejail and AppArmor. I gave up because configuring these can be quite challenging, especially since profiles need to be linked individually.

**Comment by Frost-Phoenix** [comment]
> Additionally, there’s another point to consider: Are you aiming to keep your NixOS configuration minimal, or are you looking to develop it into something more visually and functionally advanced?

I want to keep it some what minimalism on the visual aspect but making it more functionally advanced is definitely one of my current goal. Because while I like the rather minimalism look, I don't like how it affected the usability, there are some things that clearly needs to be improved. Also for the visual part, even if I don't plan on making it super advanced, there is obviously a lot of room for improvement so suggesting are welcome.

**Comment by Frost-Phoenix** [comment]
> Integrating dotfiles into Home Manager can be quite challenging, especially when it comes to visual aspects like selecting themes, changing the style of Waybar, or choosing layouts.

Yea, it work great with one theme but I didn't find a way to do dynamic themes, but I really like the declarative aspect of it so for know I don't plan on changing that but could be a thing to do in the future.

> Additionally, discussing improvements for Rofi, creating configurations for security software

What kind or security software are you thinking about ? I don't think I ever used that kind of software so I don't really know witch one would be interesting / useful.

> sharing ideas for alternative software could be very beneficial. Therefore, opening a pinned issue for these discussions would be a great idea.

Will do :+1:

**Comment by Frost-Phoenix** [comment]
Closing as the initial issue is resolved, the ongoing conversation can continue in #42.
