### ISSUE TITLE
Timeout when building source

### ISSUE THREAD

**Issue by rares9301** [Frost-Phoenix/nixos-config#45]
2nd install here. When there are about 12-10 packages left to build, install wont go past that, giving the following error: 
Warning: Problem : timeout...

**Comment by rares9301** [comment]
1 dependency of derivation ... soundwire-3.0
same for
home-manager-path
home-manager-genera..
user-environment
etc
nixos-system-laptop

**Comment by rares9301** [comment]
1 dependency of derivation ... soundwire-3.0
same for
home-manager-path
home-manager-genera..
user-environment
etc
nixos-system-laptop

**Comment by rares9301** [comment]
after running nix log for source.drv
i got this:
webarchive:// georigielabs.net ://SoundWire_Server_linux64.tar.gz
failed to connect to web.archive.org pott 443... cannot download source from any mirrof.

**Comment by Frost-Phoenix** [comment]
This is strange... So the link to download the package is down so this is why you get a timeout. I removed the package in question from the config, you should be able to pull the changes and build now.

Thanks you notifying me about this, and let me know if it works now :+1:

**Comment by rares9301** [comment]
Yup. Might need a new mirror for the soundwire :p

**Comment by Frost-Phoenix** [comment]
I was about to open an issue for it on the nixpkgs repo but it seems to work again. Maybe it was just a small downtime of the server. So I re-added it to the config and it doesn't seem to cause any issues.

Let me know if it is also fixed for you.

**Comment by rares9301** [comment]
Works as of now. Closing issue. Thanks for your implication.
