### ISSUE TITLE
Error During NixOS Rice Installation: ms-vscode-cpptools.zip Build Failure

### ISSUE THREAD

**Issue by shreethaar** [Frost-Phoenix/nixos-config#52]
Encountered an error while installing rice on NixOS. The build for `ms-vscode-cpptools.zip` fails with the following message:

```bash
error: builder for '/nix/store/2dgl1kzzz5gadysasdlg9w9cz0azj3zh-ms-vscode-cpptools.zip.drv' failed with exit code 1;
last 7 log lines:

trying https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/1.22.2/assetbyname/Microsof
% Total % Received % Xferd Average Speed Time Current Dload Upload Left Speed

611931
61 63.8M
509k
0 0:03:28
0:02:08
0:01:20 717k

curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
error: cannot download ms-vscode-cpptools.zip from any mirror
```

Caused by: `ms-vscode-cpptools` assest server

**My solution:**
- git checkout 6986fc39dc1371cbee27b9bf3003f0bfec74aae9

I am not sure whether the issue arise because of misconfiguration at `flake.nix` or `vscodium.nix`
PS: I don't use vscode, nvim works fine for me

**Comment by Frost-Phoenix** [comment]
Hi,

I don't think this is due to a configuration error, but rather a download issue. From what I can see, it seems that curl caused the error after something went wrong with the download. I've encountered similar curl download errors before, and usually, rebuilding solves the problem.

Could you try rebuilding again to see if the error disappears?

**Comment by shreethaar** [comment]
Understood, will try it out again.

**Comment by Frost-Phoenix** [comment]
> Understood, will try it out again.

Did it work ?

**Comment by shreethaar** [comment]
> > Understood, will try it out again.
> 
> Did it work ?

Yup it finally works, it seems a little patience is required 😂
