### ISSUE TITLE
 Run-time dependency wireplumber-0.4 found: NO (tried pkgconfig)

### ISSUE THREAD

**Issue by deng232** [Frost-Phoenix/nixos-config#8]
```
building the system configuration...
these 18 derivations will be built:
  /nix/store/wicfikhl5axaska0b2ggc23ks1l569a0-hm_.vscodeossextensions.extensionsimmutable.json.drv
  /nix/store/pmxapw7bm7606bf8jl928yr893zfspsi-wlroots-hyprland-2024-03-09_50eae51.drv
  /nix/store/dmvg1y9n8zy4rdv3b0p3rdxqi5ayiwr9-hyprland-0.37.1+date=2024-03-21_4c79668.drv
  /nix/store/i19nx7zjipj5x6dzlfr71wz5yhvkjhl3-catppuccin-papirus-folders-unstable-2023-08-02.drv
  /nix/store/pf7i4pkjf7i7aswz7zsf5spz1j8xqrpb-nerdfonts-3.1.1.drv
  /nix/store/rl0kipsbyrsfvjg6va3mgmyavja0dg6a-skia-aseprite-m102.drv
  /nix/store/sap86pa4zi52hsl6rg24mr3ivnj1jv1x-aseprite-1.3.2.drv
  /nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv
  /nix/store/nrhip1llmm6v1qppfv1xqyfq09lfikqx-home-manager-path.drv
  /nix/store/xsimz7cimc7rmxzdsl84pf9q01w5d6ic-hm_fontconfigconf.d10hmfonts.conf.drv
  /nix/store/4r0a5zmfjsr0jlkixzsha102szh655ka-home-manager-files.drv
  /nix/store/4wnj3mmcn6mcrg9rkjyjvnavi4lr4kc2-activation-script.drv
  /nix/store/xh7yx0zvwmaiwrk7xpmz6sqmch5xa19x-home-manager-generation.drv
  /nix/store/10v6y8abcmmvdpx3jry4053lfpf7y7j9-unit-home-manager-deng.service.drv
  /nix/store/5lqvg6wmq5d8jwbnhp7672lsqxnanjgk-user-environment.drv
  /nix/store/jhbdlys9jdz2b9pbbqydm1y86akl8n8h-system-units.drv
  /nix/store/pa4vfg5f62hni1pkff24hsrnykrpw35d-etc.drv
  /nix/store/242hyii87n5pl2agzi8ihjqskay624s5-nixos-system-nixos-24.05.20240319.b06025f.drv
building '/nix/store/i19nx7zjipj5x6dzlfr71wz5yhvkjhl3-catppuccin-papirus-folders-unstable-2023-08-02.drv'...
building '/nix/store/pf7i4pkjf7i7aswz7zsf5spz1j8xqrpb-nerdfonts-3.1.1.drv'...
building '/nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv'...
building '/nix/store/wicfikhl5axaska0b2ggc23ks1l569a0-hm_.vscodeossextensions.extensionsimmutable.json.drv'...
building '/nix/store/rl0kipsbyrsfvjg6va3mgmyavja0dg6a-skia-aseprite-m102.drv'...
error: builder for '/nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency libudev found: YES 255
       > Run-time dependency libevdev found: YES 1.13.1
       > Run-time dependency libmpdclient found: YES 2.22
       > Run-time dependency xkbregistry found: YES 1.5.0
       > Run-time dependency jack found: YES 1.9.22
       > Run-time dependency wireplumber-0.4 found: NO (tried pkgconfig)
       >
       > meson.build:95:17: ERROR: Dependency "wireplumber-0.4" not found, tried pkgconfig
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-catppuccin-papirus-folders-unstable-2023-08-02.drv-0/source/src/32x32/places': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-skia-aseprite-m102.drv-0/source': Directory not empty
error: 1 dependencies of derivation '/nix/store/nrhip1llmm6v1qppfv1xqyfq09lfikqx-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xh7yx0zvwmaiwrk7xpmz6sqmch5xa19x-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5lqvg6wmq5d8jwbnhp7672lsqxnanjgk-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pa4vfg5f62hni1pkff24hsrnykrpw35d-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/242hyii87n5pl2agzi8ihjqskay624s5-nixos-system-nixos-24.05.20240319.b06025f.drv' failed to build
```

**Comment by 0fie** [comment]
The issue was fixed. Please run 

> ```
> building the system configuration...
> these 18 derivations will be built:
>   /nix/store/wicfikhl5axaska0b2ggc23ks1l569a0-hm_.vscodeossextensions.extensionsimmutable.json.drv
>   /nix/store/pmxapw7bm7606bf8jl928yr893zfspsi-wlroots-hyprland-2024-03-09_50eae51.drv
>   /nix/store/dmvg1y9n8zy4rdv3b0p3rdxqi5ayiwr9-hyprland-0.37.1+date=2024-03-21_4c79668.drv
>   /nix/store/i19nx7zjipj5x6dzlfr71wz5yhvkjhl3-catppuccin-papirus-folders-unstable-2023-08-02.drv
>   /nix/store/pf7i4pkjf7i7aswz7zsf5spz1j8xqrpb-nerdfonts-3.1.1.drv
>   /nix/store/rl0kipsbyrsfvjg6va3mgmyavja0dg6a-skia-aseprite-m102.drv
>   /nix/store/sap86pa4zi52hsl6rg24mr3ivnj1jv1x-aseprite-1.3.2.drv
>   /nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv
>   /nix/store/nrhip1llmm6v1qppfv1xqyfq09lfikqx-home-manager-path.drv
>   /nix/store/xsimz7cimc7rmxzdsl84pf9q01w5d6ic-hm_fontconfigconf.d10hmfonts.conf.drv
>   /nix/store/4r0a5zmfjsr0jlkixzsha102szh655ka-home-manager-files.drv
>   /nix/store/4wnj3mmcn6mcrg9rkjyjvnavi4lr4kc2-activation-script.drv
>   /nix/store/xh7yx0zvwmaiwrk7xpmz6sqmch5xa19x-home-manager-generation.drv
>   /nix/store/10v6y8abcmmvdpx3jry4053lfpf7y7j9-unit-home-manager-deng.service.drv
>   /nix/store/5lqvg6wmq5d8jwbnhp7672lsqxnanjgk-user-environment.drv
>   /nix/store/jhbdlys9jdz2b9pbbqydm1y86akl8n8h-system-units.drv
>   /nix/store/pa4vfg5f62hni1pkff24hsrnykrpw35d-etc.drv
>   /nix/store/242hyii87n5pl2agzi8ihjqskay624s5-nixos-system-nixos-24.05.20240319.b06025f.drv
> building '/nix/store/i19nx7zjipj5x6dzlfr71wz5yhvkjhl3-catppuccin-papirus-folders-unstable-2023-08-02.drv'...
> building '/nix/store/pf7i4pkjf7i7aswz7zsf5spz1j8xqrpb-nerdfonts-3.1.1.drv'...
> building '/nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv'...
> building '/nix/store/wicfikhl5axaska0b2ggc23ks1l569a0-hm_.vscodeossextensions.extensionsimmutable.json.drv'...
> building '/nix/store/rl0kipsbyrsfvjg6va3mgmyavja0dg6a-skia-aseprite-m102.drv'...
> error: builder for '/nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv' failed with exit code 1;
>        last 10 log lines:
>        > Run-time dependency libudev found: YES 255
>        > Run-time dependency libevdev found: YES 1.13.1
>        > Run-time dependency libmpdclient found: YES 2.22
>        > Run-time dependency xkbregistry found: YES 1.5.0
>        > Run-time dependency jack found: YES 1.9.22
>        > Run-time dependency wireplumber-0.4 found: NO (tried pkgconfig)
>        >
>        > meson.build:95:17: ERROR: Dependency "wireplumber-0.4" not found, tried pkgconfig
>        >
>        > A full log can be found at /build/source/build/meson-logs/meson-log.txt
>        For full logs, run 'nix log /nix/store/zkf9r3va8bfbndsgpg7mzfmwkwjkh8ip-waybar-0.10.0.drv'.
> error (ignored): error: cannot unlink '/tmp/nix-build-catppuccin-papirus-folders-unstable-2023-08-02.drv-0/source/src/32x32/places': Directory not empty
> error (ignored): error: cannot unlink '/tmp/nix-build-skia-aseprite-m102.drv-0/source': Directory not empty
> error: 1 dependencies of derivation '/nix/store/nrhip1llmm6v1qppfv1xqyfq09lfikqx-home-manager-path.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/xh7yx0zvwmaiwrk7xpmz6sqmch5xa19x-home-manager-generation.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/5lqvg6wmq5d8jwbnhp7672lsqxnanjgk-user-environment.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/pa4vfg5f62hni1pkff24hsrnykrpw35d-etc.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/242hyii87n5pl2agzi8ihjqskay624s5-nixos-system-nixos-24.05.20240319.b06025f.drv' failed to build
> ```

The issue was resolved a few days ago. Please run `nix flake update` and then rebuild your system.
